import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    rules: {
      "no-unused-vars": "off",
      "no-undef": "off",
      "no-console": "off",
      "no-debugger": "off",
      "no-empty": "off",
      "no-extra-semi": "off",
      "no-fallthrough": "off",
      "no-irregular-whitespace": "off",
      "no-mixed-spaces-and-tabs": "off",
      "no-redeclare": "off",
      "no-unexpected-multiline": "off",
      "no-unreachable": "off",
      "no-unsafe-finally": "off",
      "no-unsafe-negation": "off",
      "no-useless-escape": "off",
      "require-yield": "off",
      "use-isnan": "off",
      "valid-typeof": "off",
      "no-case-declarations": "off",
      "no-compare-neg-zero": "off",
      "no-cond-assign": "off",
      "no-constant-condition": "off",
      "no-control-regex": "off",
      "no-dupe-args": "off",
      "no-dupe-keys": "off",
      "no-duplicate-case": "off",
      "no-empty-character-class": "off",
      "no-ex-assign": "off",
      "no-func-assign": "off",
      "no-inner-declarations": "off",
      "no-invalid-regexp": "off",
      "no-obj-calls": "off",
      "no-regex-spaces": "off",
      "no-sparse-arrays": "off",
      "no-template-curly-in-string": "off",
      "no-unexpected-multiline": "off",
      "no-unreachable": "off",
      "no-unsafe-finally": "off",
      "no-unsafe-negation": "off",
      "no-unused-labels": "off",
      "no-useless-catch": "off",
      "no-useless-escape": "off",
      "no-with": "off",
      "require-atomic-updates": "off",
      "require-yield": "off",
      "use-isnan": "off",
      "valid-typeof": "off",
      "default-case": "off",
      "default-case-last": "off",
      "default-param-last": "off",
      "eqeqeq": "off",
      "grouped-accessor-pairs": "off",
      "guard-for-in": "off",
      "max-classes-per-file": "off",
      "no-alert": "off",
      "no-caller": "off",
      "no-constructor-return": "off",
      "no-div-regex": "off",
      "no-else-return": "off",
      "no-empty-function": "off",
      "no-eq-null": "off",
      "no-eval": "off",
      "no-extend-native": "off",
      "no-extra-bind": "off",
      "no-extra-label": "off",
      "no-floating-decimal": "off",
      "no-global-assign": "off",
      "no-implicit-coercion": "off",
      "no-implicit-globals": "off",
      "no-implied-eval": "off",
      "no-iterator": "off",
      "no-labels": "off",
      "no-lone-blocks": "off",
      "no-loop-func": "off",
      "no-magic-numbers": "off",
      "no-multi-spaces": "off",
      "no-multi-str": "off",
      "no-new": "off",
      "no-new-func": "off",
      "no-new-wrappers": "off",
      "no-octal": "off",
      "no-octal-escape": "off",
      "no-param-reassign": "off",
      "no-proto": "off",
      "no-return-assign": "off",
      "no-return-await": "off",
      "no-script-url": "off",
      "no-self-assign": "off",
      "no-self-compare": "off",
      "no-sequences": "off",
      "no-throw-literal": "off",
      "no-unmodified-loop-condition": "off",
      "no-unused-expressions": "off",
      "no-unused-labels": "off",
      "no-useless-call": "off",
      "no-useless-concat": "off",
      "no-useless-return": "off",
      "no-void": "off",
      "prefer-named-capture-group": "off",
      "prefer-promise-reject-errors": "off",
      "prefer-regex-literals": "off",
      "radix": "off",
      "require-await": "off",
      "require-unicode-regexp": "off",
      "strict": "off",
      "yoda": "off",
      "jsx-a11y/alt-text": "off",
      "@typescript-eslint/ban-ts-comment": "off",
    
    },
  },
];

export default eslintConfig;